export { default as DashboardView } from './views/Dashboard.vue'
export { default as SettingsView } from './views/SettingsView.vue'
export { default as Sidebar } from './components/dashboard/Sidebar.vue'
export { default as SidebarMobile } from './components/dashboard/SidebarMobile.vue'
export { default as UserAccountPopup } from './components/dashboard/UserAccountPopup.vue'
export { default as SuccessToastNotification } from './components/common/SuccessToastNotification.vue'
export { default as DeletePostModal } from './components/common/DeletePostModal.vue'
export { default as Cards } from './components/common/Cards.vue'
export { default as Logo } from './components/common/Logo.vue'
export { default as Tooltip } from './components/common/Tooltip.vue'


export { default as SignInView } from './views/auth/SignIn.vue'
export { default as SignUpView } from './views/auth/SignUp.vue'
export { default as EmailValidationView } from './views/auth/EmailValidation.vue'
export { default as PasswordView } from './views/auth/Password.vue'
export { default as ForgotPasswordView } from './views/auth/ForgotPassword.vue'
export { default as ResetLinkView } from './views/auth/ResetLink.vue'
export { default as ResetPasswordView } from './views/auth/ResetPassword.vue'
export { default as PasswordUpdationView } from './views/auth/PasswordUpdation.vue'
export { default as AccountDeletedView } from './views/AccountDeleted.vue'

export { default as BrandingSection } from './components/auth/BrandingSection.vue'
export { default as NotificationsView } from './components/notifications/NotificationsView.vue'
export { default as PromptBox } from './components/promptBox/PromptBox.vue'
export { default as SchedulerCalendarModal } from './components/calendar/SchedulerCalendarModal.vue'
export { default as ChatActionBar } from './components/chat/ActionBar.vue'
